# Generated by Django 5.1.7 on 2025-07-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_encoderprofile_institution_type_alter_user_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="rsvp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="rsvp_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
